# Generated by Django 4.1.4 on 2023-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(max_length=1024, verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
    ]
