# Generated by Django 4.1.4 on 2023-02-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_notes', '0002_alter_learn_notes_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_notes',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='作者'),
        ),
    ]
