# Generated by Django 4.1.4 on 2023-02-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_notes', '0003_learn_notes_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_notes',
            name='username',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='作者'),
        ),
    ]
