# Generated by Django 4.1.4 on 2023-03-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_notes', '0007_alter_learn_notes_create_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn_notes',
            name='content',
        ),
    ]
