# Generated by Django 4.1.4 on 2023-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_notes', '0008_remove_learn_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_notes',
            name='num_likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
