# Generated by Django 4.1.4 on 2023-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=32, verbose_name='年龄')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
