# Generated by Django 4.1.4 on 2023-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_department_userinfo_delete_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
