# Generated by Django 4.1.4 on 2023-02-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_learn_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learn_Notes',
        ),
    ]
