# Generated by Django 4.1.4 on 2023-02-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminTable',
        ),
    ]
