# Generated by Django 4.1.4 on 2023-03-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_admintable_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintable',
            options={'verbose_name': '添加用户', 'verbose_name_plural': '添加用户'},
        ),
    ]
